const firebaseErrors = {
  "auth/invalid-email": "Invalid email address",
  "auth/user-disabled": "User account has been disabled",
  "auth/user-not-found": "User not found",
  "auth/wrong-password": "Wrong password",
  "auth/email-already-in-use": "Email already in use",
  "auth/operation-not-allowed": "Operation not allowed",
  "auth/weak-password": "Password is too weak",
  "auth/invalid-credential": "Invalid credential",
  "auth/invalid-verification-code": "Invalid verification code",
  "auth/invalid-verification-id": "Invalid verification id",
  "auth/missing-verification-code": "Missing verification code",
  "auth/missing-verification-id": "Missing verification id",
  "auth/phone-number-already-exists": "Phone number already exists",
  "auth/invalid-phone-number": "Invalid phone number",
  "auth/missing-phone-number": "Missing phone number",
  "auth/quota-exceeded": "Quota exceeded",
  "auth/captcha-check-failed": "Captcha check failed",
  "auth/invalid-app-credential": "Invalid app credential",
  "auth/invalid-app-id": "Invalid app id",
  "auth/invalid-verification-payload": "Invalid verification payload",
  "auth/invalid-recipient-email": "Invalid recipient email",
  "auth/missing-app-credential": "Missing app credential",
  "auth/missing-app-id": "Missing app id",
  "auth/missing-verification-payload": "Missing verification payload",
  "auth/missing-recipient-email": "Missing recipient email",
  "auth/invalid-tenant-id": "Invalid tenant id",
  "auth/missing-tenant-id": "Missing tenant id",
  "auth/tenant-id-mismatch": "Tenant id mismatch",
  "auth/invalid-argument": "Invalid argument",
  "auth/invalid-creation-time": "Invalid creation time",
  "auth/invalid-disabled-field": "Invalid disabled field",
  "auth/invalid-display-name": "Invalid display name",
  "auth/invalid-email-verified": "Invalid email verified",
  "auth/invalid-hash-algorithm": "Invalid hash algorithm",
  "auth/invalid-hash-block-size": "Invalid hash block size",
  "auth/invalid-hash-derived-key-length": "Invalid hash derived key length",
  "auth/invalid-hash-key": "Invalid",
}

export default firebaseErrors
